version: '3.1'

services:

  aria2:
    build:
      context: aria2
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    user: "${CURRENT_UID}:${CURRENT_GID}"
    expose:
      - 6800
    networks:
      - bgmi
    environment:
      - ARIA2_TOKEN=${ARIA2_TOKEN}
      - BGMI_TOKEN=${BGMI_TOKEN}
    volumes:
      - ./aria2/.aria2/:/aria2/
      - ./data/downloads/:/downloads/
      - ./.bgmi:/bgmi

  nginx:
    image: nginx:1.16-alpine
    ports:
      - "${PORT}:80"
    links:
      - aria2
      - bgmi
    networks:
      - bgmi
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ariang/:/ariang/
      - ${HOST_BGMI_PATH}:/bgmi

  bgmi:
    build:
      context: ./bgmi
      args:
        BGMI_VERSION: dev
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}

    user: "${CURRENT_UID}:${CURRENT_GID}"

    networks:
      - bgmi
    expose:
      - 8888
    environment:
      - ARIA2_TOKEN=${ARIA2_TOKEN}
      - BGMI_TOKEN=${BGMI_TOKEN}
    volumes:
      - ${HOST_BGMI_PATH}:/bgmi

networks:
  bgmi:
    driver: bridge
